class DefaultCategories {
  static const List<Map<String, dynamic>> categories = [
    {
      'id': 'food_dining',
      'name': 'Food & Dining',
      'icon_name': 'restaurant',
      'color_hex': '#FF5722',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'groceries',
      'name': 'Groceries',
      'icon_name': 'shopping_cart',
      'color_hex': '#4CAF50',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'transportation',
      'name': 'Transportation',
      'icon_name': 'directions_car',
      'color_hex': '#2196F3',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'shopping',
      'name': 'Shopping',
      'icon_name': 'shopping_bag',
      'color_hex': '#E91E63',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'entertainment',
      'name': 'Entertainment',
      'icon_name': 'movie',
      'color_hex': '#9C27B0',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'utilities',
      'name': 'Utilities',
      'icon_name': 'bolt',
      'color_hex': '#FF9800',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'healthcare',
      'name': 'Healthcare',
      'icon_name': 'medical_services',
      'color_hex': '#F44336',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'education',
      'name': 'Education',
      'icon_name': 'school',
      'color_hex': '#3F51B5',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'personal',
      'name': 'Personal Care',
      'icon_name': 'spa',
      'color_hex': '#00BCD4',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'travel',
      'name': 'Travel',
      'icon_name': 'flight',
      'color_hex': '#009688',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'bills',
      'name': 'Bills & Fees',
      'icon_name': 'receipt',
      'color_hex': '#795548',
      'type': 'expense',
      'is_default': true,
    },
    {
      'id': 'other',
      'name': 'Other',
      'icon_name': 'more_horiz',
      'color_hex': '#607D8B',
      'type': 'expense',
      'is_default': true,
    },
    // Income categories
    {
      'id': 'salary',
      'name': 'Salary',
      'icon_name': 'attach_money',
      'color_hex': '#4CAF50',
      'type': 'income',
      'is_default': true,
    },
    {
      'id': 'freelance',
      'name': 'Freelance',
      'icon_name': 'work',
      'color_hex': '#8BC34A',
      'type': 'income',
      'is_default': true,
    },
    {
      'id': 'investment',
      'name': 'Investment',
      'icon_name': 'trending_up',
      'color_hex': '#CDDC39',
      'type': 'income',
      'is_default': true,
    },
  ];
}
